name: jitsi_meet_wrapper_example
description: Demonstrates how to use the jitsi_meet_wrapper plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  jitsi_meet_wrapper:
    path: ../

  flutter_zoom_sdk:
    git:
      url: https://git.dromedian.it/mobile/concilium-flutter/flutter_zoom_sdk
      ref: "8091fbf0"

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
